grafana:
  image: grafana/grafana:6.5.0
  ports:
    - 3000:3000
  volumes:
    - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
  environment:
    GF_INSTALL_PLUGINS: grafana-worldmap-panel
    GF_AUTH_DISABLE_LOGIN_FORM: "true"
    GF_AUTH_ANONYMOUS_ENABLED: "true"
    GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"